services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zoonk_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/app
      - ./priv/cert:/app/priv/cert:ro
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

volumes:
  postgres_data:
